In [140]:
import numpy as np
import pandas as pd

In [99]:
np.array([0, 0, 1, 0])

array([0, 0, 1, 0])

In [100]:
np.zeros((5, 7, 2, 3, 4, 5))

array([[[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0.,

In [101]:
grid_world = np.zeros((4, 4))
agent_position = grid_world[0, 0]
agent_position = grid_world[-1, -1]
grid_world

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
frame_stack = np.zeros((4, 84, 84))
frame_stack[0, 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
action_probs = np.array([0.1, 0.2, 0.5, 0.2])
if np.sum(action_probs) != 1:
    print("There is same thing wrong")

In [104]:
random_action = np.random.choice(action_probs, p=action_probs)
random_action

np.float64(0.2)

In [105]:
n_states, n_actions = 10, 4
q_table = np.zeros((n_states, n_actions))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
optimistic_q = np.ones((n_states, n_actions)) * 10.0
optimistic_q

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [107]:
state, action = 4, 1
q_table[state, action] = 1.5
q_table

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ]])

In [113]:
best_action = np.argmax(q_table[state])
best_action

np.int64(1)

In [120]:
np.random.random()

0.5628810132008196

In [139]:
data = {}
for i in range(10_000_00):
    item = np.random.randint(10)
    if item not in data:
        data[item] = 1
    else:
        data[item] += 1

data

{6: 100424,
 0: 99716,
 9: 100204,
 3: 100115,
 1: 99584,
 7: 99717,
 5: 100289,
 2: 99846,
 8: 100098,
 4: 100007}

In [155]:
de = pd.Series(data).describe()
de

count        10.000000
mean     100000.000000
std         275.944439
min       99584.000000
25%       99749.250000
50%      100052.500000
75%      100181.750000
max      100424.000000
dtype: float64

In [161]:
de.max()

np.float64(100424.0)

In [208]:
np.mean(np.random.randint(1, 10, 100000))

np.float64(5.00276)

In [162]:
buffer_size = 1000
state_dim = 4

states = np.zeros((buffer_size, state_dim))
actions = np.zeros(buffer_size, dtype=np.int32)
rewards = np.zeros(buffer_size)
next_states = np.zeros((buffer_size, state_dim))
dones = np.zeros(buffer_size, dtype=np.bool_)

In [240]:
state = np.array([0.1, 0.5, 0.2, 0.8])
weights = np.array([1.0, 2.0, -0.5, 1.5])

# state @ weights
state @ state
weights @ weights

np.float64(7.5)

In [242]:
def linear_value_function(state, weights):
    return np.dot(state, weights)

# Example state and weights
state = np.array([0.1, 0.5, 0.2, 0.8])
weights = np.array([1.0, 2.0, -0.5, 1.5])

# Approximate value
value = linear_value_function(state, weights)
print(f"Approximate value for state: {value:.3f}")

# Updating weights with gradient descent
def update_weights(state, target, prediction, weights, alpha=0.01):
    # TD error
    error = target - prediction
    print(f"Error: {error:f}")
    # Gradient is just the feature vector (state) for linear approximation
    gradient = state
    # Update rule: w += α * δ * ∇_w V(s)
    return weights +  error * alpha * state

# Example update
target_value = 500

for i in range(100):
    # print("Original weights:", weights)
    prediction = linear_value_function(state, weights)
    print(f"Prediction: {prediction:f}")
    weights = update_weights(state, target_value, prediction, weights)

Approximate value for state: 2.200
Prediction: 2.200000
Error: 497.800000
Prediction: 6.879320
Error: 493.120680
Prediction: 11.514654
Error: 488.485346
Prediction: 16.106417
Error: 483.893583
Prediction: 20.655016
Error: 479.344984
Prediction: 25.160859
Error: 474.839141
Prediction: 29.624347
Error: 470.375653
Prediction: 34.045878
Error: 465.954122
Prediction: 38.425847
Error: 461.574153
Prediction: 42.764644
Error: 457.235356
Prediction: 47.062656
Error: 452.937344
Prediction: 51.320267
Error: 448.679733
Prediction: 55.537857
Error: 444.462143
Prediction: 59.715801
Error: 440.284199
Prediction: 63.854472
Error: 436.145528
Prediction: 67.954240
Error: 432.045760
Prediction: 72.015471
Error: 427.984529
Prediction: 76.038525
Error: 423.961475
Prediction: 80.023763
Error: 419.976237
Prediction: 83.971540
Error: 416.028460
Prediction: 87.882207
Error: 412.117793
Prediction: 91.756114
Error: 408.243886
Prediction: 95.593607
Error: 404.406393
Prediction: 99.395027
Error: 400.604973
Predict

In [245]:
np.random.rand(10, 4)
np.random.rand(4)

array([0.49637575, 0.25804964, 0.75745472, 0.79455582])